"""rename field

Revision ID: ad5c363b91c3
Revises: 2fc53ac68dee
Create Date: 2025-09-09 09:23:02.332638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad5c363b91c3'
down_revision: Union[str, Sequence[str], None] = '2fc53ac68dee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('content', sa.Text(), nullable=False))
    op.drop_column('articles', 'contents')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('contents', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('articles', 'content')
    # ### end Alembic commands ###
